#!/usr/bin/env escript
%%! -pa ebin

main([Arg]) ->
  recorder:analyze(Arg),
  halt(0);
main(_Args) ->
  Error = "ERROR: Please give a single beam file as argument to the script.\n",
  io:format(Error),
  halt(1).
